package com.example.demo.model;

import java.util.Date;

public class MsgComment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msgcomment.id
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msgcomment.publishId
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    private Integer publishid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msgcomment.userId
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msgcomment.name
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msgcomment.comment
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msgcomment.createTime
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msgcomment.id
     *
     * @return the value of msgcomment.id
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msgcomment.id
     *
     * @param id the value for msgcomment.id
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msgcomment.publishId
     *
     * @return the value of msgcomment.publishId
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    public Integer getPublishid() {
        return publishid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msgcomment.publishId
     *
     * @param publishid the value for msgcomment.publishId
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    public void setPublishid(Integer publishid) {
        this.publishid = publishid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msgcomment.userId
     *
     * @return the value of msgcomment.userId
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msgcomment.userId
     *
     * @param userid the value for msgcomment.userId
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msgcomment.name
     *
     * @return the value of msgcomment.name
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msgcomment.name
     *
     * @param name the value for msgcomment.name
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msgcomment.comment
     *
     * @return the value of msgcomment.comment
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msgcomment.comment
     *
     * @param comment the value for msgcomment.comment
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msgcomment.createTime
     *
     * @return the value of msgcomment.createTime
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msgcomment.createTime
     *
     * @param createtime the value for msgcomment.createTime
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}