package com.example.demo.model;

import java.util.Date;

public class Publish {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column publish.id
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column publish.name
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column publish.userid
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column publish.title
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column publish.content
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column publish.publishUrl
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    private String publishurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column publish.updataTime
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    private Date updatatime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column publish.createTime
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column publish.id
     *
     * @return the value of publish.id
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column publish.id
     *
     * @param id the value for publish.id
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column publish.name
     *
     * @return the value of publish.name
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column publish.name
     *
     * @param name the value for publish.name
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column publish.userid
     *
     * @return the value of publish.userid
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column publish.userid
     *
     * @param userid the value for publish.userid
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column publish.title
     *
     * @return the value of publish.title
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column publish.title
     *
     * @param title the value for publish.title
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column publish.content
     *
     * @return the value of publish.content
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column publish.content
     *
     * @param content the value for publish.content
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column publish.publishUrl
     *
     * @return the value of publish.publishUrl
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    public String getPublishurl() {
        return publishurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column publish.publishUrl
     *
     * @param publishurl the value for publish.publishUrl
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    public void setPublishurl(String publishurl) {
        this.publishurl = publishurl == null ? null : publishurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column publish.updataTime
     *
     * @return the value of publish.updataTime
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    public Date getUpdatatime() {
        return updatatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column publish.updataTime
     *
     * @param updatatime the value for publish.updataTime
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    public void setUpdatatime(Date updatatime) {
        this.updatatime = updatatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column publish.createTime
     *
     * @return the value of publish.createTime
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column publish.createTime
     *
     * @param createtime the value for publish.createTime
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}