package com.example.demo.model;

import java.util.Date;

public class SignLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign_log.id
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign_log.accountId
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    private Integer accountid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign_log.account
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign_log.userId
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign_log.password
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign_log.name
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign_log.age
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign_log.createTime
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign_log.type
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    private Integer type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign_log.id
     *
     * @return the value of sign_log.id
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign_log.id
     *
     * @param id the value for sign_log.id
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign_log.accountId
     *
     * @return the value of sign_log.accountId
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    public Integer getAccountid() {
        return accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign_log.accountId
     *
     * @param accountid the value for sign_log.accountId
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    public void setAccountid(Integer accountid) {
        this.accountid = accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign_log.account
     *
     * @return the value of sign_log.account
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign_log.account
     *
     * @param account the value for sign_log.account
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign_log.userId
     *
     * @return the value of sign_log.userId
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign_log.userId
     *
     * @param userid the value for sign_log.userId
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign_log.password
     *
     * @return the value of sign_log.password
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign_log.password
     *
     * @param password the value for sign_log.password
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign_log.name
     *
     * @return the value of sign_log.name
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign_log.name
     *
     * @param name the value for sign_log.name
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign_log.age
     *
     * @return the value of sign_log.age
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign_log.age
     *
     * @param age the value for sign_log.age
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign_log.createTime
     *
     * @return the value of sign_log.createTime
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign_log.createTime
     *
     * @param createtime the value for sign_log.createTime
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign_log.type
     *
     * @return the value of sign_log.type
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign_log.type
     *
     * @param type the value for sign_log.type
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }
}