package com.example.demo.model;

public class StudentForm {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_form.id
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_form.account
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_form.age
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_form.name
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_form.password
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_form.token
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    private String token;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_form.id
     *
     * @return the value of student_form.id
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_form.id
     *
     * @param id the value for student_form.id
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_form.account
     *
     * @return the value of student_form.account
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_form.account
     *
     * @param account the value for student_form.account
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_form.age
     *
     * @return the value of student_form.age
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_form.age
     *
     * @param age the value for student_form.age
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_form.name
     *
     * @return the value of student_form.name
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_form.name
     *
     * @param name the value for student_form.name
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_form.password
     *
     * @return the value of student_form.password
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_form.password
     *
     * @param password the value for student_form.password
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_form.token
     *
     * @return the value of student_form.token
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_form.token
     *
     * @param token the value for student_form.token
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }
}