package com.example.demo.mapper;

import com.example.demo.model.LoginCheck;
import com.example.demo.model.LoginCheckExample;
import java.util.List;


import org.apache.ibatis.annotations.Param;

public interface LoginCheckMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logincheck
     *
     * @mbg.generated Thu Jan 02 18:05:06 CST 2020
     */
    long countByExample(LoginCheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logincheck
     *
     * @mbg.generated Thu Jan 02 18:05:06 CST 2020
     */
    int deleteByExample(LoginCheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logincheck
     *
     * @mbg.generated Thu Jan 02 18:05:06 CST 2020
     */
    int insert(LoginCheck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logincheck
     *
     * @mbg.generated Thu Jan 02 18:05:06 CST 2020
     */
    int insertSelective(LoginCheck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logincheck
     *
     * @mbg.generated Thu Jan 02 18:05:06 CST 2020
     */
    List<LoginCheck> selectByExample(LoginCheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logincheck
     *
     * @mbg.generated Thu Jan 02 18:05:06 CST 2020
     */
    int updateByExampleSelective(@Param("record") LoginCheck record, @Param("example") LoginCheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logincheck
     *
     * @mbg.generated Thu Jan 02 18:05:06 CST 2020
     */
    int updateByExample(@Param("record") LoginCheck record, @Param("example") LoginCheckExample example);
}