package com.example.demo.mapper;

import com.example.demo.model.Publish;
import com.example.demo.model.PublishExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PublishMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    Integer countByExample(PublishExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    int deleteByExample(PublishExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    int insert(Publish record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    int insertSelective(Publish record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    List<Publish> selectByExample(PublishExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    Publish selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    int updateByExampleSelective(@Param("record") Publish record, @Param("example") PublishExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    int updateByExample(@Param("record") Publish record, @Param("example") PublishExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    int updateByPrimaryKeySelective(Publish record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    int updateByPrimaryKey(Publish record);

    List<Publish> selectAllPublish(@Param("index") Integer index,
                                   @Param("size") Integer size,
                                   @Param("content") String content);
}