package com.example.demo.mapper;

import com.example.demo.model.StudentForm;
import com.example.demo.model.StudentFormExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StudentFormMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_form
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    long countByExample(StudentFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_form
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    int deleteByExample(StudentFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_form
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_form
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    int insert(StudentForm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_form
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    int insertSelective(StudentForm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_form
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    List<StudentForm> selectByExample(StudentFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_form
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    StudentForm selectByPrimaryKey(Integer id);

    //返回单条实体
    StudentForm selectByOneExample(StudentFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_form
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    int updateByExampleSelective(@Param("record") StudentForm record, @Param("example") StudentFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_form
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    int updateByExample(@Param("record") StudentForm record, @Param("example") StudentFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_form
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    int updateByPrimaryKeySelective(StudentForm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_form
     *
     * @mbg.generated Thu Jan 02 17:46:13 CST 2020
     */
    int updateByPrimaryKey(StudentForm record);
}